[package]
name = "tasd-edit"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "3.0.10"
byteorder = "1.4"
crossterm = "0.21"
regex = "1.5"
chrono = "0.4"
strum = "0.21"
strum_macros = "0.21"
dyn-clone = "1"
#colored = "2"